### ISSUE TITLE
Impossible ajouter tranche

### ISSUE THREAD

**Issue by pierr0t** [thelia-modules/CustomDelivery#2]
Bonjour,

J'arrive à activer le module, à faire le réglage prix/poids/taxes et à faire qu'il soit enregistré quand j'y reviens, par contre, impossible d'ajouter une tranche, le clic sur le "+" est sans effet ... Le formulaire s'est bien modifié (que le poids si j'ai choisi poids par ex.), mais le "+" ne fait rien et ma tranche a disparu si je ressors/reviens.

**Comment by bibich** [comment]
Quand je fais un test je n'ai pas le problème. 
Tu es sur quel navigateur ? 
As-tu une erreur javascript sur la page, peut-être causée par un autre module et qui empêcherait le chargement du javascript du module ?

**Comment by pierr0t** [comment]
Bonjour,

Je viens de tester sur Mac avec Firefox, Chromium et Safari, marche pas.
Sur PC W7pro64, sur IE10 et FF tout à jour, marche pas.

Le site est en 2.1.2, il n'y a pas bcp de modules activés, keywords, Colissimo, franco de port, CMCIC, c'est tout. Maintenant il n'est pas exclu que je ne comprenne pas le principe même si ça me semble simple ... Et la console javascript ne me donne pas d'erreur, rien ne s'ajoute quand je clique sur "+".

J'ai aussi essayé en désactivant rapidos Colissimo et Franco de port, pareil ... Je n'ai pas touché aux templates de backoffice.
Si besoin d'autres essais, je suis dispo !
Pierre

**Comment by InformatiqueProg** [comment]
Bonjour,
J'ai le même problème que pierr0t et je suis aussi sur Thélia 2.1.2

Le problème semble venir de 

```
{hook name="module.config-js" location="module-config-js" modulecode="$module_code"}
```

Le contenu du fichier "module-config-js.html" ne s'ajoute pas.
Par contre, si le supprime l'argument `modulecode`, le contenu du fichier "module-config-js.html" du module `CustomDelivery` et `Colissimo` s'ajoutent...

J'ai cherché dans le code, mais je n'ai pas trouvé la solution du problème...

**Comment by gillesbourgeat** [comment]
Bonjour, il y a une erreur sur le hook en base de donnée.
Il ne faut pas supprimer modulecode.
Par contre il faut mettre la valeur by_module à 1 pour ce hook

``` sql
UPDATE  `test`.`hook` SET  `by_module` =  '1' WHERE  `hook`.`code` ='module.config-js';
```

Après il faut vider le cache.

Le problème était présent dans l'alpha 2 de la version 2.1
Problème de mise à jour sql

Cordialement,

**Comment by pierr0t** [comment]
Bonjour,
Il suffit que je passe cette commande SQL et ça règle le problème ... futures mises à jour comprises ?
Pierre

**Comment by gillesbourgeat** [comment]
Oui,
Ne pas oublier de vider le cache.
A vérifier que dans le template module-configure.html du backoffice il y ai bien la ligne 

``` smarty
{hook name="module.config-js" location="module-config-js" modulecode="$module_code"}
```

**Comment by gillesbourgeat** [comment]
Le `+` ne fonctionne pas chez vous car le javascript du module n'est pas chargé.

**Comment by pierr0t** [comment]
Commence mal j'ai pas de table 'test' ... ? Thelia 2.1.5 ... (si je comprends bien la commande SQL proposée mais ça je pense que ça va:-)

**Comment by pierr0t** [comment]
En tous cas j'ai bien ça dans module-configure.html du backoffice:

<code>
{block name="javascript-last-call"}
    {hook name="module.config-js" location="module-config-js" modulecode="$module_code"}
    {hook name="wysiwyg.js" location="wysiwyg-module-config-js" }
{/block}
</code>

**Comment by gillesbourgeat** [comment]
Oups c'est pas test, mais le nom de votre base de données
Vous pouvez faire

``` sql
UPDATE  `hook` SET  `by_module` =  '1' WHERE  `hook`.`code` ='module.config-js';
```

**Comment by pierr0t** [comment]
Ok cette dernière commande semble avoir débloqué les choses, merci !

Autres questions/suggestion
- que pensez-vous de la possibilité de créer plusieurs tranches dans l'autre sens, c'est à dire par ex proposer un "standard" et un "express" avec pour chacune de ces tranches les fonctionnalités actuelles ? (pensez-vous possible que je duplique ce module en CustomDeliveryExpress en changeant toutes les variables et namespaces pour me simuler cette 2 tranche ?)
- il pourrait être intéressant d'avoir un champ de commentaires pour chaque tranche (par ex pour signaler le franco au delà d'une certaine tranche)
- il pourrait aussi être intéressant d'avoir une manière de traiter les zones non couvertes, c'est à dire par ex spécifier des tarifs France, Europe et pouvoir dire au delà "nous consulter", ou pouvoir faire un commentaire sur les zones pour spécifier un délai de livraison (France J+5, Europe J+8)

Pierre.

**Comment by gillesbourgeat** [comment]
Can you opens a new issue for this request
